steps:
  - name: "node"
    id: "Installing dependencies"
    entrypoint: "yarn"
    args: ["--frozen-lockfile"]
  
  - name: "node"
    id: "Building app"
    entrypoint: "yarn"
    args:
      - "build"

  - name: gcr.io/cloud-builders/gsutil
    id: "Copying to Cloud storage"
    args: ["-m", "rsync", "-d", "-r", "build", "gs://epms-doc.fbase.co.uk"]

  # Invalidate CDN cache for the Load balancer
  - name: gcr.io/cloud-builders/gcloud
    id: "Invalidating CDN Cache"
    args: ["compute", "url-maps", "invalidate-cdn-cache", "epms-doc-lb", "--path", "/*", "--async"]

  

logsBucket: 'gs://cloudbuild_logs-e0e8e91e'