steps:
  - name: "node"
    entrypoint: "yarn"
  
  - name: "node"
    entrypoint: "yarn"
    args:
      - "build"
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "-r", "build", "gs://e-pms-doc.fbase.co.uk"]

  

logsBucket: 'gs://cloudbuild_logs-e0e8e91e'