steps:
  - name: "node"
    entrypoint: "yarn"
  
  - name: "node"
    entrypoint: "yarn"
    args:
      - "build"

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-d", "-r", "build", "gs://epms-doc.fbase.co.uk"]

  - name: gcr.io/cloud-builders/gcloud
    args: ["compute", "url-maps", "invalidate-cdn-cache", "epms-doc-lb", "--path", "/*", "--async"]

  

logsBucket: 'gs://cloudbuild_logs-e0e8e91e'